CHANGES.txt, pom.xml, src/main/java/io/split/client/LocalhostSplitManager.java, src/main/java/io/split/client/SplitClientImpl.java, src/main/java/io/split/client/SplitManager.java, src/main/java/io/split/client/SplitManagerImpl.java, src/main/java/io/split/engine/experiments/ParsedSplit.java, src/main/java/io/split/engine/matchers/BetweenMatcher.java, src/main/java/io/split/engine/matchers/EqualToMatcher.java, src/main/java/io/split/engine/matchers/GreaterThanOrEqualToMatcher.java, src/main/java/io/split/engine/matchers/LessThanOrEqualToMatcher.java, src/test/java/io/split/client/SplitManagerImplTest.java
Jira Ticket: [SPLIT-2315](https://splitio.atlassian.net/browse/SPLIT-2315)
=> Adding access to the SplitNames functionality

CHANGES.txt, pom.xml, src/main/java/io/split/client/ChangeNumberExceptionWrapper.java, src/main/java/io/split/client/SplitClientImpl.java, src/main/java/io/split/client/dtos/KeyImpression.java, src/main/java/io/split/client/impressions/ImpressionsManager.java, src/main/java/io/split/engine/impressions/TreatmentLog.java, src/test/java/io/split/client/SplitClientImplTest.java, src/test/java/io/split/client/impressions/ImpressionsManagerTest.java
ChangeNumber of the Split that served an impression should be sent as part of the impression.
=> Change numbers in impressions

client/src/main/java/io/split/client/LocalhostSplitFactory.java
this fixes https://github.com/splitio/java-client/issues/41
=> [fix] daemonize split local file

client/src/main/java/io/split/client/AbstractLocalhostSplitFile.java, client/src/main/java/io/split/client/LocalhostSplitFactory.java
Addresses github issue https://github.com/splitio/java-client/issues/84
=> Localhost windows

client/CHANGES.txt, client/pom.xml, client/src/main/java/io/split/client/SplitClientImpl.java, client/src/test/java/io/split/client/SplitClientImplTest.java, pom.xml, testing/pom.xml
* fix missing value when properties are sent
* update CHANGES.txt & version number
=> fix missing value when properties are sent (#89)

client/CHANGES.txt, client/pom.xml, pom.xml, testing/pom.xml
=> Shade guava too

client/pom.xml, client/src/main/java/io/split/engine/common/Backoff.java, client/src/main/java/io/split/engine/common/PushManager.java, client/src/main/java/io/split/engine/common/PushManagerImp.java, client/src/main/java/io/split/engine/common/SyncManagerImp.java, client/src/main/java/io/split/engine/common/SynchronizerImp.java, client/src/main/java/io/split/engine/experiments/RefreshableSplitFetcherProvider.java, client/src/main/java/io/split/engine/segments/RefreshableSegmentFetcher.java, client/src/main/java/io/split/engine/sse/AuthApiClientImp.java, client/src/main/java/io/split/engine/sse/EventSourceClient.java, client/src/main/java/io/split/engine/sse/EventSourceClientImp.java, client/src/main/java/io/split/engine/sse/NotificationProcessorImp.java, client/src/main/java/io/split/engine/sse/SSEHandler.java, client/src/main/java/io/split/engine/sse/SSEHandlerImp.java, client/src/main/java/io/split/engine/sse/SplitSseEventSource.java, client/src/main/java/io/split/engine/sse/StatusMessage.java, client/src/main/java/io/split/engine/sse/dtos/ControlNotification.java, client/src/main/java/io/split/engine/sse/dtos/ErrorNotification.java, client/src/main/java/io/split/engine/sse/dtos/OccupancyNotification.java, client/src/main/java/io/split/engine/sse/dtos/SegmentChangeNotification.java, client/src/main/java/io/split/engine/sse/dtos/SplitChangeNotification.java, client/src/main/java/io/split/engine/sse/dtos/SplitKillNotification.java, client/src/main/java/io/split/engine/sse/listeners/FeedbackLoopListener.java, client/src/test/java/io/split/engine/common/BackoffTest.java, client/src/test/java/io/split/engine/common/PushManagerTest.java, client/src/test/java/io/split/engine/common/SyncManagerTest.java, client/src/test/java/io/split/engine/common/SynchronizerTest.java, client/src/test/java/io/split/engine/sse/AuthApiClientTest.java, client/src/test/java/io/split/engine/sse/NotificationParserTest.java, client/src/test/java/io/split/engine/sse/SSEHandlerTest.java
- SSE custom implementation
- Backoff implementation 
- Improvements
=> SSE implementation changes

client/src/main/java/io/split/engine/sse/PushStatusTrackerImp.java, client/src/main/java/io/split/engine/sse/dtos/OccupancyNotification.java, client/src/test/java/io/split/engine/sse/PushStatusTrackerTest.java
=> Adding second region

client/CHANGES.txt, client/pom.xml, pom.xml, testing/pom.xml
=> Releasing 4.1.4

client/pom.xml, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomSplitAdapterConsumer.java, pluggable-storage/pom.xml, pom.xml, redis-wrapper/pom.xml, redis-wrapper/src/main/java/redis/RedisException.java, redis-wrapper/src/main/java/redis/RedisImp.java, redis-wrapper/src/test/java/redis/RedisImpTest.java, testing/pom.xml
Adding expire for events and impressions
=> Redis exceptions

client/CHANGES.txt, client/pom.xml, client/src/test/java/io/split/client/SplitClientIntegrationTest.java, pluggable-storage/pom.xml, pom.xml, redis-wrapper/pom.xml, testing/pom.xml
SDKS-5749: org.apache.httpcomponents.client5:httpclient5 conflict
SDKS-5702: Java SDK CVE Vulnerabilities
=> SDKS-5749 Shaded dependencies and vulnerability fix

client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/main/java/io/split/client/impressions/RedisImpressionSender.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomImpressionAdapterProducer.java, client/src/main/java/io/split/storages/pluggable/domain/PrefixAdapter.java, client/src/main/java/io/split/storages/pluggable/domain/SafeUserStorageWrapper.java, client/src/main/java/io/split/storages/pluggable/synchronizer/TelemetryConsumerSubmitter.java, client/src/test/java/io/split/client/impressions/RedisImpressionSenderTest.java, client/src/test/java/io/split/storages/pluggable/CustomStorageWrapperImp.java, client/src/test/java/io/split/storages/pluggable/synchronizer/TelemetryConsumerSubmitterTest.java, pluggable-storage/src/main/java/pluggable/CustomStorageWrapper.java, redis-wrapper/src/main/java/redis/RedisImp.java, redis-wrapper/src/test/java/redis/RedisImpTest.java
- Create Redis Impression sender
- Implement postCounters in RedisImpressionSender
- Implement synchronizeUniqueKeys  in TelemetryConsumerSubmitter
=> [SDKS-5854] Create Redis Impression Sender and add sendUniqueKeys in TelemetryConsumerSubmitter

client/src/main/java/io/split/client/SplitClientConfig.java, client/src/main/java/io/split/engine/common/SyncManagerImp.java, client/src/test/java/io/split/engine/common/SyncManagerTest.java
- Updated SyncManagerImp start and shutdown to fix the bug.
=> [SDKS-5987] Destroy does not stops all threads

client/src/main/java/io/split/client/SplitClientConfig.java, client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/main/java/io/split/client/events/EventsStorageConsumer.java, client/src/main/java/io/split/client/events/EventsTask.java, client/src/main/java/io/split/client/events/InMemoryEventsStorage.java, client/src/main/java/io/split/client/events/NoopEventsStorageImp.java, client/src/main/java/io/split/engine/sse/client/SSEClient.java, client/src/main/java/io/split/service/HttpPostImp.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomEventAdapterConsumer.java, client/src/main/java/io/split/telemetry/synchronizer/TelemetryInMemorySubmitter.java, client/src/test/java/io/split/client/SplitClientIntegrationTest.java, client/src/test/java/io/split/client/events/EventsTaskTest.java
- Add SchedulerExecutorService for send, flush, and pop Events.
- Add start method
- Update close to send and flush events
=> [SDKS-5498] Refactor EventTask

pluggable-storage/pom.xml, pom.xml, redis-wrapper/pom.xml, testing/pom.xml
- Update configuration and distributionManagement in the pom files.
=> Update pom files

client/CHANGES.txt, client/pom.xml, pluggable-storage/pom.xml, pom.xml, redis-wrapper/pom.xml, testing/pom.xml
- Update pom file version to 4.4.5 to release the fix for synchronizing segments
- Update changes file
=> [SDKS-5932] Update pom file to 4.4.5 and changes file

pom.xml
- Update pom file because it wasn't working the release to sonatype.
=> Update id to ossrh in pom file for sonatype

client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/main/java/io/split/client/impressions/RedisImpressionSender.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomEventAdapterProducer.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomImpressionAdapterProducer.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomSegmentAdapterConsumer.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomSegmentAdapterProducer.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomSplitAdapterConsumer.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomSplitAdapterProducer.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomTelemetryAdapterProducer.java, client/src/main/java/io/split/storages/pluggable/domain/userStorageWrapper.java, client/src/main/java/io/split/storages/pluggable/synchronizer/TelemetryConsumerSubmitter.java, client/src/test/java/io/split/client/SplitFactoryImplTest.java, client/src/test/java/io/split/client/impressions/RedisImpressionSenderTest.java, client/src/test/java/io/split/storages/pluggable/adapters/UserCustomImpressionAdapterProducerTest.java, client/src/test/java/io/split/storages/pluggable/adapters/UserCustomSegmentAdapterConsumerTest.java, client/src/test/java/io/split/storages/pluggable/adapters/UserCustomSegmentAdapterProducerTest.java, client/src/test/java/io/split/storages/pluggable/adapters/UserCustomSplitAdapterConsumerTest.java, client/src/test/java/io/split/storages/pluggable/adapters/UserCustomSplitAdapterProducerTest.java, client/src/test/java/io/split/storages/pluggable/adapters/UserCustomTelemetryAdapterProducerTest.java, client/src/test/java/io/split/storages/pluggable/domain/UserStorageWrapperTest.java, client/src/test/java/io/split/storages/pluggable/synchronizer/TelemetryConsumerSubmitterTest.java
- Update the class name SafeUserStorageWrapper to UserStorageWrapper
=> Change name SafeUserStorageWrapper to UserStorageWrapper

client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/main/java/io/split/client/events/EventsTask.java, client/src/main/java/io/split/client/impressions/ImpressionsManager.java, client/src/main/java/io/split/client/impressions/ImpressionsManagerImpl.java, client/src/main/java/io/split/engine/common/PushManagerImp.java, client/src/main/java/io/split/engine/common/SplitAPI.java, client/src/main/java/io/split/engine/common/SplitTasks.java, client/src/main/java/io/split/engine/common/SyncManagerImp.java, client/src/main/java/io/split/telemetry/synchronizer/TelemetrySyncTask.java, client/src/test/java/io/split/client/events/EventsTaskTest.java, client/src/test/java/io/split/engine/common/SyncManagerTest.java, client/src/test/java/io/split/telemetry/synchronizer/TelemetrySyncTaskTest.java
- TelemetrySyncTask startScheduledTask.
- ImpressionManagerImp start
- EventsTask start
=> [SDKS-6007] Move all starts to SyncManagerImpl

redis-wrapper/src/main/java/redis/RedisImp.java, redis-wrapper/src/main/java/redis/common/CommonRedis.java, redis-wrapper/src/test/java/redis/RedisImpTest.java
- Move buildKeyWithPrefix to CommonRedis
=> Create CommonRedis to have common methods

client/pom.xml, client/src/main/java/io/split/client/SplitManagerImpl.java, client/src/main/java/io/split/storages/SplitCacheConsumer.java, client/src/main/java/io/split/storages/memory/InMemoryCacheImp.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomSplitAdapterConsumer.java, client/src/main/java/io/split/storages/pluggable/domain/PrefixAdapter.java, client/src/test/java/io/split/client/SplitManagerImplTest.java, pluggable-storage/pom.xml, pom.xml, redis-wrapper/pom.xml, redis-wrapper/src/main/java/redis/RedisImp.java, redis-wrapper/src/test/java/redis/RedisImpTest.java, testing/pom.xml
- Create method splitNames in SplitCacheConsumer.
- Implement method in UserCustomSplitAdapterConsumer and InMemoryCacheImp.
- Update SplitManagerImpl splitNames method to use getSplits.
=> Resolving bug in QOS

README.md, client/pom.xml, pom.xml
- Update Java version to 8.
- Add property maven.compiler.source
=> PR suggestions, update Java version and pom files

client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/test/java/io/split/client/SplitClientConfigTest.java
- Update default refresh rate for features and segments
=> [SDKS-6095] Update default polling rates

client/pom.xml, client/src/main/java/io/split/client/dtos/KeyImpression.java, client/src/test/java/io/split/client/impressions/ImpressionsManagerImplTest.java, pluggable-storage/pom.xml, pom.xml, redis-wrapper/pom.xml, redis-wrapper/src/main/java/redis/RedisImp.java, redis-wrapper/src/main/java/redis/common/CommonRedis.java, redis-wrapper/src/test/java/redis/RedisImpTest.java, testing/pom.xml
- Add pt in fromImpression
- Update [ImpressionsManagerImplTest
- Update org.yaml:snakeyaml version to 1.31 to fix a vulnerability
=> Add pt in fromImpression

CHANGES.txt, client/pom.xml, client/src/test/java/io/split/client/SplitClientIntegrationTest.java, pluggable-storage/pom.xml, pom.xml, redis-wrapper/pom.xml, testing/pom.xml
- Removed ignore test from SplitClientIntegrationTest.
- Update snakeyaml version to fix a vulnerability.
- Update Changeslog.
=> [SDKS-6111] Update SplitClientIntegrationTest and snakeyaml version

client/pom.xml, client/src/main/java/io/split/client/SplitClientConfig.java, client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/main/java/io/split/client/impressions/ImpressionsManagerImpl.java, client/src/main/java/io/split/engine/common/SyncManagerImp.java, client/src/test/java/io/split/client/impressions/ImpressionsManagerImplTest.java, pluggable-storage/pom.xml, pom.xml, redis-wrapper/pom.xml, testing/pom.xml
- Remove create ProcessImpressionStrategy from ImpressionManager start.
- Create ProcessImpressionStrategy in SplitFactoryImpl
=> Refactor ImpressionManager start and create some instance in SplitFactory

client/pom.xml, client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/main/java/io/split/client/impressions/UniqueKeysTrackerImp.java, client/src/main/java/io/split/engine/common/SplitAPI.java, client/src/main/java/io/split/engine/common/SyncManager.java, client/src/main/java/io/split/engine/common/SyncManagerImp.java, client/src/test/java/io/split/engine/common/SyncManagerTest.java, pluggable-storage/pom.xml, pom.xml, redis-wrapper/pom.xml, testing/pom.xml
- Add sseclient close in SyncManagerImp
- Remove ImpressionManager close from SplitFactory's destroy
=> Add httpClient and sseclient close in SyncManagerImp

client/src/main/java/io/split/client/SplitClientConfig.java, client/src/main/java/io/split/client/SplitClientImpl.java, client/src/main/java/io/split/client/SplitFactoryBuilder.java, client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/main/java/io/split/client/impressions/ImpressionsManagerImpl.java, client/src/main/java/io/split/engine/common/LocalhostSyncManager.java, client/src/main/java/io/split/engine/common/SyncManagerImp.java, client/src/main/java/io/split/engine/experiments/SplitFetcherImp.java, client/src/test/java/io/split/client/impressions/ImpressionsManagerImplTest.java, client/src/test/java/io/split/engine/common/SyncManagerTest.java
- Add Segment SegmentSynchronizationTask to the current flow
- Add segmentDirectory to the config
- Fix log message in SplitClientImpl
=> [SDKS-6387] Add SegmentSynchronizationTask to current flow

client/src/main/java/io/split/client/LocalhostSegmentChangeFetcher.java, client/src/main/java/io/split/client/LocalhostSegmentFetcherNoop.java, client/src/main/java/io/split/client/SplitClientConfig.java, client/src/main/java/io/split/client/SplitFactoryBuilder.java, client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/main/java/io/split/engine/common/LocalhostSynchronizer.java, client/src/test/java/io/split/client/utils/LocalhostSegmentChangeFetcherTest.java, client/src/test/java/io/split/engine/common/LocalhostSynchronizerTest.java, client/src/test/java/io/split/engine/segments/SegmentSynchronizationTaskImpTest.java
- Add localhostRefreshEnable config
- Fix the case that the segmentDirectory config is null.
=> [SDKS-6350] Add refreshEnable config for localhost

CHANGES.txt, client/pom.xml, client/src/main/java/io/split/client/LegacyLocalhostSplitChangeFetcher.java, client/src/main/java/io/split/client/SplitClientConfig.java, client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/main/java/io/split/client/impressions/strategy/ProcessImpressionOptimized.java, client/src/main/java/io/split/client/utils/LocalhostSanitizer.java, client/src/main/java/io/split/engine/common/SyncManagerImp.java, client/src/main/java/io/split/engine/evaluator/EvaluatorImp.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomImpressionAdapterProducer.java, client/src/main/java/io/split/storages/pluggable/synchronizer/TelemetryConsumerSubmitter.java, client/src/test/java/io/split/client/events/EventsSenderTest.java, pluggable-storage/pom.xml, pom.xml, redis-wrapper/pom.xml, redis-wrapper/src/main/java/redis/RedisCluster.java, redis-wrapper/src/main/java/redis/RedisInstance.java, redis-wrapper/src/main/java/redis/RedisPipeline.java, redis-wrapper/src/main/java/redis/RedisSingle.java, testing/pom.xml
- Update client version and change log
- Add some changes after check sonarqube
=> [SDKS-6577] Updated client version and change log

client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/main/java/io/split/client/utils/FeatureFlagProcessor.java, client/src/main/java/io/split/client/utils/FeatureFlagsToUpdate.java, client/src/main/java/io/split/engine/experiments/SplitFetcherImp.java, client/src/main/java/io/split/engine/experiments/SplitParser.java, client/src/main/java/io/split/engine/sse/workers/FeatureFlagWorkerImp.java, client/src/test/java/io/split/client/utils/FeatureFlagProcessorTest.java, client/src/test/java/io/split/engine/common/LocalhostSynchronizerTest.java, client/src/test/java/io/split/engine/experiments/SplitFetcherImpTest.java, client/src/test/java/io/split/engine/experiments/SplitFetcherTest.java, client/src/test/java/io/split/engine/experiments/SplitSynchronizationTaskTest.java, client/src/test/java/io/split/engine/segments/SegmentSynchronizationTaskImpTest.java
Created processFeatureFlagChanges method. It returns a FeatureFlagsToUpdate, that it'll use to update the SplitCache.
=> [SDKS-7087] Use SplitCache update in SplitFetcherImp

client/src/main/java/io/split/client/CacheUpdaterService.java, client/src/main/java/io/split/client/SplitFactoryImpl.java, client/src/main/java/io/split/engine/experiments/ParsedSplit.java, client/src/main/java/io/split/engine/experiments/SplitParser.java, client/src/main/java/io/split/storages/SplitCacheConsumer.java, client/src/main/java/io/split/storages/memory/InMemoryCacheImp.java, client/src/main/java/io/split/storages/pluggable/adapters/UserCustomSplitAdapterConsumer.java, client/src/test/java/io/split/client/CacheUpdaterServiceTest.java, client/src/test/java/io/split/client/SplitClientImplTest.java, client/src/test/java/io/split/client/SplitManagerImplTest.java, client/src/test/java/io/split/engine/common/LocalhostSynchronizerTest.java, client/src/test/java/io/split/engine/common/SynchronizerTest.java, client/src/test/java/io/split/engine/evaluator/EvaluatorIntegrationTest.java, client/src/test/java/io/split/engine/evaluator/EvaluatorTest.java, client/src/test/java/io/split/engine/experiments/SplitFetcherImpTest.java, client/src/test/java/io/split/engine/experiments/SplitFetcherTest.java, client/src/test/java/io/split/engine/experiments/SplitParserTest.java, client/src/test/java/io/split/engine/experiments/SplitSynchronizationTaskTest.java, client/src/test/java/io/split/engine/segments/SegmentSynchronizationTaskImpTest.java, client/src/test/java/io/split/engine/sse/workers/FeatureFlagWorkerImpTest.java, client/src/test/java/io/split/storages/memory/InMemoryCacheTest.java
- Implement GetNamesByFlagSets
- Update methods: update, remove, and add.
=> [SDKS-7518] Add flagSets in InMemoryCacheImp
